### ISSUE TITLE
Initial zoom problem  and loading state

### ISSUE THREAD

**Issue by barsukov** [imgly/imgly-sdk-html5#63] opened 2015-07-20 09:55 UTC
I think this problem reference by #59  issue. Because the first zoom is wrong, every time when I start this kit, I have preloading picture with a wrong size and reason of it is 100% zoom level(when allowed maximum for fit is 46 or other) . I think this can happen probably because I have this strange Loading text in lef corner. And I can do every operations and whatever, but this Loading and ```<div class="imglykit-loadingOverlay">``` div has not gone.
1) This is the first loading this kit by ```kit.run()``` command.
![screenshot 2015-07-20 11 43 16](https://cloud.githubusercontent.com/assets/1594996/8773500/fe8def8a-2ed4-11e5-8028-3ce764fea001.png)
2) This is screanshot after any operations, that is became immdiatly to norm zoom level and fit picture almost correct but still with this loading text.
![screenshot 2015-07-20 11 43 29](https://cloud.githubusercontent.com/assets/1594996/8773649/15e91906-2ed6-11e5-9cbb-32a00a8c7e0b.png)

**Comment by saschagehlich** [comment] 2015-07-20 09:56
I don't think it has something to do with the loading label - it should not be visible though. Did you replace your CSS when you updated to the latest version?

**Comment by barsukov** [comment] 2015-07-20 09:58
Hm I do not remember my last update. My current version is "2.0.0-beta.12" is it last one?

**Comment by saschagehlich** [comment] 2015-07-20 09:59
No, the latest version is beta.16 - but I think we updated the CSS with beta.12. You might have to replace the CSS to make the loading indicator disappear initially.

**Comment by barsukov** [comment] 2015-07-20 10:00
Ok thank you, and what about this zoom?

**Comment by barsukov** [comment] 2015-07-20 15:02
I updated to 16 beta and loading text problem is over, but zoom problem is still there.

**Comment by saschagehlich** [comment] 2015-08-03 12:16
Duplicate of #59

**Closed by saschagehlich** 2015-08-03 12:16 UTC
